#jirabase is ubuntu with the jira install complete, doesn't run as a service
from kizzie/jirabase
maintainer Kat McIvor <kat.mcivor at qa.com>

expose 8005
expose 8080

entrypoint /opt/atlassian/jira/bin/start-jira.sh -fg
