from php:5.6-apache
maintainer Kat McIvor

#install php-mysql 
#run apt-get install php5-mysql -y
run docker-php-ext-install mysql mysqli pdo pdo_mysql

COPY php/ /var/www/html/
COPY setup/php.ini /usr/local/etc/php/
